name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Backend
      run: |
        pip install -r requirements.txt
        python -m pytest app/tests/ -v
      env:
        DATABASE_URL: mysql+pymysql://test:test@localhost:3306/test_db

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Test Frontend
      working-directory: ./crew-schedule-ui
      run: |
        npm ci
        npm test -- --watchAll=false

  build:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Backend Image
      run: docker build -t crew-backend .
    - name: Build Frontend Image
      run: docker build -t crew-frontend ./crew-schedule-ui