name: Build and Test

on:
  workflow_dispatch:
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Backend Image
      run: docker build -t crew-backend .

    - name: Build Frontend Image  
      run: docker build -t crew-frontend ./crew-schedule-ui

    - name: Test Backend
      run: |
        pip install -r requirements.txt
        python -m pytest app/tests/ -v

    # - Jest config issue
    # - name: Test Frontend
    #   working-directory: ./crew-schedule-ui
    #   run: |
    #     npm ci
    #     npm test