name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Backend
      run: |
        pip install -r requirements.txt
        python -m pytest app/tests/ -v
      env:
        DATABASE_URL: mysql+pymysql://test:test@localhost:3306/test_db

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Backend Image
      run: docker build -t crew-backend .
    - name: Build Frontend Image
      run: docker build -t crew-frontend ./crew-schedule-ui